import { DatabaseSync } from 'node:sqlite';
const d = new DatabaseSync('D:/webkaifa/server/data/news.db', { readOnly: true });
const zero = d.prepare("SELECT COUNT(*) AS n FROM posts WHERE views = 0").get().n;
const crawledZero = d.prepare("SELECT COUNT(*) AS n FROM posts WHERE views = 0 AND source_url IS NOT NULL").get().n;
const total = d.prepare('SELECT COUNT(*) AS n FROM posts').get().n;
const totalCrawled = d.prepare('SELECT COUNT(*) AS n FROM posts WHERE source_url IS NOT NULL').get().n;
console.log(`total=${total} crawled=${totalCrawled} views0=${zero} crawledViews0=${crawledZero}`);
const sample = d.prepare('SELECT id, title, views FROM posts ORDER BY id DESC LIMIT 8').all();
sample.forEach(r => console.log(`  #${r.id} views=${r.views} ${String(r.title).slice(0, 40)}`));
const maxView = d.prepare('SELECT MAX(views) AS m FROM posts').get().m;
console.log('max views:', maxView);
d.close();
